[language-server]
emmet-lsp = { command = "emmet-language-server", args = [ "--stdio" ]}
tailwindcss-ls = { command = "tailwindcss-language-server", args = ["--stdio"] }

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "emmet-lsp", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "emmet-lsp", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "emmet-lsp", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "emmet-lsp", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "emmet-lsp", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "emmet-lsp", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
